In [13]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import 
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd

In [8]:
iris = load_iris()

In [14]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [15]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [19]:
df['target'] = iris.target

In [20]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [24]:
X = df.drop(['target'], axis='columns')
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [26]:
y = df.target
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

### Logistic Regression

In [27]:
l_scores = cross_val_score(LogisticRegression(), X, y)
l_scores

/Users/nikhilbansal/opt/anaconda3/envs/MLPipeline/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [28]:
np.average(l_scores)

0.9733333333333334

### SVM

In [43]:
svc_scores = cross_val_score(SVC(), X, y)
svc_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [42]:
np.average(svc_scores)

0.9666666666666666

### Decision Tree

In [34]:
dt_scores = cross_val_score(DecisionTreeClassifier(), X, y)
dt_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [35]:
np.average(dt_scores)

0.9666666666666668

### Random Classifier

In [39]:
ran_cl = cross_val_score(RandomForestClassifier(n_estimators=40), X, y)
ran_cl

array([0.96666667, 0.96666667, 0.93333333, 0.9       , 1.        ])

In [40]:
np.average(ran_cl)

0.9533333333333334